### ISSUE TITLE
Obtaining image from MagicIcon

### ISSUE THREAD

**Issue by ShawnieBoy** [ShawnieBoy/magarenaCardBuilder#4]
Mana costs for `MagicCard` are held in `MagicCard.getCost().getIcons()` as a `List<MagicIcon>`

The mana icons themselves for `MagicIcon` are held as an iconIndex for the Mana.png file.

What would be the best way to pull the images out - re-reference a separate Mana.png file?

I'd like to be able to pull them in reverse order and `.drawImage` them from right to left until none remain in the` List<MagicIcon>`

**Comment by lodici** [comment]
See [IconImages](https://github.com/magarena/magarena/blob/master/src/magic/ui/IconImages.java). It loads the png spritesheet into MANA_ICON_SHEET and uses ``getManaIcon`` to extract the icons and caches them in ``manaIcons``.
- [MANA_ICON_SHEET](https://github.com/magarena/magarena/blob/master/src/magic/ui/IconImages.java#L39)
- [manaIcons](https://github.com/magarena/magarena/blob/master/src/magic/ui/IconImages.java#L20) 
- [getManaIcon()](https://github.com/magarena/magarena/blob/master/src/magic/ui/IconImages.java#L75)

**Comment by ShawnieBoy** [comment]
Goctha - I saw it was returning a key, but forgot that it's the ImageIcon related to that key.

Thanks

**Comment by ShawnieBoy** [comment]
Ahh, see where I was having problems, it's private

**Comment by lodici** [comment]
Yes, the public API is ``getSmallManaIcon`` and ~~``getBigMamaIcon``~~ ``getBigManaIcon``.

**Comment by ShawnieBoy** [comment]
:grinning: 

They're both private too - shall I make them public?

**Comment by lodici** [comment]
My bad.

> They're both private too - shall I make them public?

Up to you - if you are actually using a copy of the IconImages class then just remove what you don't need, whatever makes it easier for you.

**Comment by ShawnieBoy** [comment]
I'll just make it public and reference.

Also, it looks as though none of them have the 'shadow' which appears for card casting costs. We only seem to have the images for mana symbols which appear in ability texts.

**Comment by lodici** [comment]
![mana](https://cloud.githubusercontent.com/assets/2443519/7221926/c6d0403a-e6f8-11e4-90c0-02be699fcd28.png)

Not sure what you mean by "shadow"?

**Comment by ShawnieBoy** [comment]
![mana_circle](https://cloud.githubusercontent.com/assets/2363180/7221923/b11764e4-e6f8-11e4-9383-0a5defe1cbcc.png)

vs

![mana_circle](https://cloud.githubusercontent.com/assets/2363180/7221924/b8675ae2-e6f8-11e4-895c-d261164eb955.png)

**Comment by ShawnieBoy** [comment]
Compare mana cost and mana activation here:


![](http://magiccards.info/scans/en/m15/213.jpg)

**Comment by lodici** [comment]
You could actually do that dynamically - draw a black circle slightly offset then draw mana symbol on top. Or you could create a ``mana-shadow.png`` :wink:

**Comment by ShawnieBoy** [comment]
I think I may use separate references - could spend the rest of my life trying to get the shadow right.

**Comment by ShawnieBoy** [comment]
My ocd's already witching with the font kerning...

**Comment by lodici** [comment]
Version 2 then.

**Comment by ShawnieBoy** [comment]
This issue was moved to lodici/magarena-cardbuilder#4
